config/routes.rb
Rails.application.routes.draw do
  get '/todos/deleteactivity' , controller: 'todos' , actions: 'deleteactivity'
  get '/todos/listactivities' , controller: 'todos' , actions: 'listactivities'
  post '/todos/createactivity' , controller: 'todos' , actions: 'createactivity'
  get '/todos/home' , controller: 'todos' , actions: 'home'
get '/todos/populate' , controller: 'todos' , actions: 'populate'
  get '/users/populate' , controller: 'users' , actions: 'populate'
post '/todos/verify' , controller: 'todos' , actions: 'todos'
post '/todos/insertintodb' , controller: 'todos' , actions: 'insertintodb'
get '/todos/insert' , controller: 'todos' , actions: 'insert'

get '/users/logout' , controller: 'users' , actions: 'logout'
get '/users/admin' , controller: 'users' , actions: 'admin'
get '/users/login' , controller: 'users', action: 'login'
  post '/users/verify' , controller: 'users', action: 'verify'
  resources :users 

  

  

  resources :todos 
   root 'todos#home'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
		def change
	create table :activities do |t|
		t.text :job
		t.timestamps
	end
end
end

app/models/todo.rb
class Todo < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
	validates :mailid , presence: true , uniqueness: true , length: { minimum: 5 }
	validates :password , presence: true , length: { minimum: 6}
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  def insert
    
  end

  def home
  end

  def createactivity
    info = params[:t]
    record = Activity.new(job:params[:t])
    record.save
    info = 1
    render :text => record.to_json.to_s
  
  end

  def deleteactivity
    id = params[:id]
    record = Activity.find(id)
    record.destroy
    #info = 1
    render :text => id.to_json.to_s 
  end

  def listactivities
 users = Activity.all
  render :text => users.to_json.to_s

  end


  def verify
    
    @records = User.all
    @records.each do |record| 
      info = info + ":" + record.task + "," + record.status
    end
        render :text => @records.to_json.to_s
      #render :json { :success => 1 , :info => @info }    
  end
  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  def login
  
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.save
    #render json: { :success => 1, :todo => @todo } 
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:task, :status, :createdAt, :completedAt)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
 skip_before_filter :verify_authenticity_token, :only => [:verify]
  # GET /users
  # GET /users.json
  def index
    if session[:username] == "jayaganthanjk@gmail.com"
    @users = User.all
  else
    render "secured"
  end
  end
def secured
end

def populate
  users = User.all
  render :text => users.to_json.to_s
end

  def login
    if session[:username] != nil 
      redirect_to '/todos/new'
    else
      render 'login'
    end      
    
  end


  # GET /users/1
  # GET /users/1.json
  def show
  end

  def admin
    if session[:username] == "jayaganthanjk@gmail.com"
    @users=User.all
    render 'index'
  else
    redirect_to '/todos/new'
  end
    #redirect_to '/todos/new'
  end

  def verify
    mail = params[:mailid]
    password = params[:password]
    record=User.find_by_mailid(mail)
    if record.password == password
       #@pass=true
       session[:username] = mail
       redirect_to '/todos/new'
    else 
      render 'login'
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  def logout
    session[:username] = nil
    render 'login'
  end

  # POST /users
  # POST /users.json
  def create
    if session[:username] == nil 
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    else
    redirect_to '/todos/new'
  end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:mailid, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :createdAt %><br>
    <%= f.datetime_select :createdAt %>
  </div>
  <div class="field">
    <%= f.label :completedAt %><br>
    <%= f.datetime_select :completedAt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/home.html.erb
<form method="post" action="return false" onsubmit="javascript:return false;" >
<input type="text" id="todoactivity" style="width: 319px;
padding: 6px;
border: none;
font-weight: bold;
align: center;
font-size: 20px;
border-bottom: 2px solid black;border-shadow:none;
font: bold 16px 'lucida sans', 'trebuchet MS', 'Tahoma';" placeholder="ToDo Activity.."><br>
<input type="submit" id="submitactivity" style="border: none;
background-color: transparent;
font: bold 16px 'lucida sans', 'trebuchet MS', 'Tahoma';
border-bottom: 2px solid blueviolet;" ><br>
	</form> 


<Style>
#close:hover{
	background-color:#c1c1c1;
}
#close{
	width: 16px;
height: 16px;
border: 1px solid black;
border-radius: 9px;
text-align: center;
font: bold 10px 'lucida sans', 'trebuchet MS', 'Tahoma';
cursor:default;
z-index:1000;
}
.listbox{
		width: 295px;
margin-left: 10px;
float: left;
padding: 10px;

height: 100px;
margin-top: 10px;

background-color: #3ff;
text-transform: capitalize;
font: bold 16px 'lucida sans', 'trebuchet MS', 'Tahoma';
-webkit-box-shadow:  3px 3px 14px 0px rgba(0,0,0,0.75);
-moz-box-shadow:  3px 3px 14px 0px rgba(0,0,0,0.75);
box-shadow:  3px 3px 14px 0px rgba(0,0,0,0.75);
}
input:focus{
	outline:none;
}
#timeview{
	float: right;
margin-top: -1px;
font-style: italic;
font-weight: normal;
cursor:default;
}
</style>
<br>
<script type="text/javascript">
$(document).ready(function(){
	console.log("loading content");
	function loadlist()
	{
	console.log("Showing list..");
		$.getJSON("/todos/listactivities",function(data){
			console.log("success listing..");
			for(i=0;i<data.length;i++)
			{
				console.log(data[i].created_at);
				var checck=$('#close').clone();
				var newlist = $('#list').clone().addClass("listbox").attr('data-id',data[i].id);
				newlist.html('<div id="close" style="float right;align:right;" data-id="'+data[i].id+'">X</div><br>'+data[i].job);
				newlist.prependTo('#todolist');
				checck.html('<p>Hi</p>');
				console.log(newlist.html()+"check");

			}
		});
	}
	loadlist();
});


</script>
<div id="list"></div>
<div id="todolist">	
</div>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Status</th>
      <th>Createdat</th>
      <th>Completedat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.task %></td>
        <td><%= todo.status %></td>
        <td><%= todo.createdAt %></td>
        <td><%= todo.completedAt %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/insert.html.erb
<form method="post" action="return false;" onsubmit="javascript:return false;">
<input type="text" id="todotext" name="activity" placeholder="Enter Your ToDo Here"  >
<input type="submit" value="create" id="submittodo">
</form>
<div id="list" style="height:200px;width:200px;border:1px solid black;">

	</div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

<a href="/users/logout">Logout</a>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @todo.task %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<p>
  <strong>Createdat:</strong>
  <%= @todo.createdAt %>
</p>

<p>
  <strong>Completedat:</strong>
  <%= @todo.completedAt %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mailid %><br>
    <%= f.email_field :mailid %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/admin.html.erb
<ul>
<%= @users.each do |user| %>
<li><%= user.mailid %></li>
<li><%= user.password %></li>
<% end %> 
</ul>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Mailid</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.mailid %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<a href="/users/login">Existing user<a>

app/views/users/login.html.erb
<%= form_tag("/users/verify", method: "post") do %>
  <%= label_tag(:mailid, "E-Mail:") %>
  <%= email_field_tag(:mailid) %>
  <%= label_tag(:password, "Password:") %>
  <%= password_field_tag(:password) %>
  <%= submit_tag("Login") %>
<% end %>


<%= session[:username] %>

<button id="show" >Display</button>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>


<button id="one">wow</button>

app/views/users/secured.html.erb
You have no privilages to access it...:(

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mailid:</strong>
  <%= @user.mailid %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
Hello World